name: Deploy to Production

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - run: npm ci

      - name: Deploy to Vercel (production)
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: team_vSi0ooGXG4IiO9BnZy8LwaOj
          VERCEL_PROJECT_ID: prj_EUw3Yq3owWL0okMi1Sj4fSZz27jx
